#sudo: false
language: node_js
node_js: 
 # - 10 # use nodejs v10 LTS
  - 12
cache: npm

before_install:
    - export TZ='Asia/Shanghai'

install:
  - npm install hexo #安装hexo及插件
  - npm install --save hexo-generator-index
  - npm install --save hexo-generator-archive
  - npm install --save hexo-generator-tag
#install:
#  - npm ls --depth 0

branches:
  only:
    - hexo # hexo分支保存hexo的源码；新建md在这个分支里；生成的static，在public目录，然后放到master分支
script:
  - hexo clean
  - hexo g  #  生成public目录,里面包含新的文件，比如：./public/2019/11/13/page4；
  
after_script:
  - git clone https://${GH_REF} .deploy_git  # 获得静态master分支
  - cd .deploy_git
  - git checkout master  #里面网站的静态文件，来自master分支
  - cd ../
  - mv .deploy_git/.git/ ./public/    # public里有新的文件；把线上的git记录放到准备发布到git master分支
  - cd ./public
  - git config user.name "bjdzliu"  #修改name
  - git config user.email "dezhaoliu@gmail.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push  "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称
env:
 global:
   - GH_REF: github.com/bjdzliu/bjdzliu.github.io.git

notifications:
  email:
    - liudz@citic.com
  on_success: change
  on_failure: always


#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GH_TOKEN
#  keep-history: true
#  on:
#    branch: master
#  local-dir: public
